---
title: "Hmw I : Tables and visualization"
date: "2024-01-13"
format: html
editor: visual
toc: false
highlight-style: arrow
params:
  author1: "Name1 FirstName1"
  author2: "Name2 FirstName2"
  date: "2024-01-01"
  course: "EDA"

execute:
  eval: true

engine: knitr
---

Due : January 26, 2024

### {{<  fa map >}} Objectives

This homework is dedicated to table wrangling and visualization.  

OECD offers different versions of annual GDP data and components (income, expenditure, output, ...) in different currencies, with and without PPP. 

OECD offers data on life expectancy at different territorial levels for both gendres and total population. 

OECD offers detailed data on population size at different territorial levels for both genders, and for different age ranges.

Using data gathered from OECD, build a dataframe with a gapminder-like  schema. Using `ggplot2` and `plotly`,  design an animation like the Rossling address to BBC. 

Your data and graphical pipelines should be designed so that 
they can be at least partially reused to perform gapminder-like animations 
with other kind of data gathered from OECD. For example one, could replace 
life expectancy at birth by life expectancy at 60, infant mortality, or any other health index. One could replace GDP per capita with social expenditure per capita, or something like that. 

Your deliverable shall consist in a `qmd` file that can be rendered in HTML format.

You shall describe the downloaded data. 

Plots  shall be endowed with titles, legends and captions,

Data pipelines and graphical pipelines shall be given in an appendix. 

### {{<  fa database >}} Data

Data have to be downloaded from [https://data.oecd.org](https://data.oecd.org)
(the old site [https://stats.oecd.org](https://stats.oecd.org) which could be drilled using package `OECD` is shutting down).

You shall download data pertaining to:

- Life expectancy 
- GDP 
- Population

Download data as `csv` files.

For the sake of reproducibilty, Keep track of the URLs used to download the data. A reader should be able to reproduce your steps and check that the data are indeed what you say they are. In your report, you shall state the URLs. 

Keep the downloaded data in a separate subdirectory. Your working directory 
should look like something like that: 

```{verbatim}
.
├── DATA/
│   ├── OECD.foo.csv
│   ├── OECD.foobar.csv
│   ├── OECD.bar.csv
|   :
├── _extensions/
├── _outdir/
├── _metadata.yml
├── _quarto.yml
├── my_report.qmd
└── README.md
```




## {{<  fa graduation-cap >}} Grading criteria 

{{< include _evaluation_guidelines.qmd >}}

