---
title: 'Homework 1 (2023): Data Wrangling and Visualization'
subtitle: 'Due date : 2023-02-24 23:55 (this is a hard deadline)'
author: Lagarde et Michard
date: '2023-02-24'
format:
  html:
    code-fold: true
jupyter: python3
---

# Homework 1 

Due date : **2023-02-24 @23h55** (this is a **hard deadline**)

## Fill this cell with your names

- Name, First Name, Informatique/Mathématique-Informatique
- Name, First Name, Informatique/Mathématique-Informatique

## Carefully follow instructions

**If you don't: no evaluation!**

Write in English or French

The deliverable is a file

- `xxx_yyy.ipynb` file (jupyter notebook) or 
- `xxx_yyy.py` file (if you are using `jupytext`) or
- `xxx_yyy.qmd` file (if you are using `quarto`)

where `xxx` and `yyy` are your names, for example `lagarde_michard.ipynb`. 

The deliverable is not meant to contain cell outputs.  

The data files used to execute cells are meant to sit in the same directory as the deliverable. Use relative filepaths or urls to denote the data files.   

We **will** execute the code in your notebook: make sure that running all the cells works well. 


## Grading <i class="fa graduation-cap"></i>

Here is the way we'll assess your work

| Criterion | Points | Details |
|:----------|:-------:|:----|
|Spelling and syntax | 3 | English/French  |
|Plots correction | 3 |  Clarity / answers the question  |
|Plot style and cleanliness | 3 | Titles, legends, labels, breaks ... |
|Table wrangling | 4 | ETL, SQL like manipulations |
|Computing Statistics | 5 | SQL `goup by`  and aggregation  |
|DRY compliance | 2 | DRY principle at [Wikipedia](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)|

If we see a single (or more) `for` loop in your code: **-5 points**.  Everything can be done using high-level `pandas` methods

# Preliminaries

## Notebooks: Modus operandi

- This is a [Jupyter Notebook](https://jupyter.org).
- When you execute code within the notebook, the results appear beneath the code.
- [Jupytext](https://github.com/mwouts/jupytext)
- [Quarto](https://quarto.org) 

## Packages

- Base `Python` can do a lot. But the full power of `Python` comes from a fast growing collection of `packages`/`modules`.

- Packages are first installed (that is using `pip install` or `conda install`), and if
needed, imported during a session.

- The `docker` image you are supposed to use already offers a lot of packages. You should not need to install new packages.

- Once a package has been installed on your drive, if you want all objects exported by the package to be available in your session, you should import the package, using `from pkg import *`.

- If you just want to pick some subjects from the package,
you can use qualified names like `pkg.object_name` to access the object (function, dataset, class...)

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:49:19.662376Z', start_time: '2021-02-03T09:49:19.659057Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# importing basic tools
import numpy as np
import pandas as pd

from pandas.api.types import CategoricalDtype

import os            # file operations
import requests      # networking
import zipfile
import io
from pathlib import Path

from datetime import date  # if needed


```

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:49:21.139505Z', start_time: '2021-02-03T09:49:21.136745Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# importing plotting packages
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
```

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:56:45.103619Z', start_time: '2021-02-03T09:56:45.099259Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# make pandas plotly-friendly
np.set_printoptions(precision=2, suppress=True)
%matplotlib inline
pd.options.plotting.backend = "plotly"
```

# Getting the data

## French data

The French data are built and made available by [INSEE](https://www.insee.fr/fr/accueil)  (French Governement Statistics Institute)

Prénoms:
- [https://www.insee.fr/fr/statistiques/fichier/2540004/nat2021_csv.zip](https://www.insee.fr/fr/statistiques/fichier/2540004/nat2021_csv.zip)

This dataset has been growing for a while. It has been considered by
social scientists for decades.  Given names are meant to give insights into a variety
of phenomena, including religious observance.

- A glimpse at the body of work can be found in [_L'archipel français_ by Jérome Fourquet, Le Seuil, 2019 ](https://www.seuil.com/ouvrage/l-archipel-francais-jerome-fourquet/9782021406023)

- Read the [File documentation](https://www.insee.fr/fr/statistiques/2540004?sommaire=4767262#documentation)

## US data 

US data may be gathered from 

[Baby Names USA from 1910 to 2021 (SSA)](https://www.kaggle.com/datasets/donkea/ssa-names-1910-2021?resource=download)

See [https://www.ssa.gov/oact/babynames/background.html](https://www.ssa.gov/oact/babynames/background.html)


## British data 

English and Welsh data can be gathered from 

[https://www.ons.gov.uk/](https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/datasets/babynamesinenglandandwalesfrom1996?utm_source=pocket_saves)




## Download the French data

**QUESTION:** Download the data into a file which relative path is `'./nat2021_csv.zip'`

__Hints:__

- Have a look at  package [`requests`](https://requests.readthedocs.io/en/master/).
- Use magic commands to navigate across the file hierarchy and create subdirectories when needed

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:56:54.136172Z', start_time: '2021-02-03T09:56:54.132800Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# for Frenc data 

params = dict(
    url = 'https://www.insee.fr/fr/statistiques/fichier/2540004/nat2021_csv.zip',
    dirpath = './',
    timecourse = '',
    datafile = 'nat2021.hdf',
    fpath = 'nat2021_csv.zip'
)
```

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:56:54.282784Z', start_time: '2021-02-03T09:56:54.280062Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# modify location  make sure you are in the right directory
# %cd
# %pwd  #
# %ls
# %mkdir # if needed
```

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:56:54.409700Z', start_time: '2021-02-03T09:56:54.406560Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
url = params['url']      # 'https://www.insee.fr/fr/statistiques/fichier/2540004/nat2021_csv.zip'
fpath = params['fpath']  # './nat2021_csv.zip'
```

```{python}
# your code here

if not Path(params['fpath']).exists():
    r = requests.get(params['url'])                # What is the type of `r` ?
    z = zipfile.ZipFile((io.BytesIO(r.content)))   # What is the type of `z` ? 
    z.extractall(path='./')
```

## Download US and British data 


```{python}
# your code here
```

## Load the French data in memory

**QUESTION:** Load the data in a `pandas` `DataFrame` called `data`

__Hints:__

- You should obtain a `Pandas dataframe` with 4 columns.
- Mind the conventions used to build the `csv` file.
- Package `pandas` provides the convenient tools.
- The dataset, though not too large, is already demanding.
- Don't hesitate to test your methods on a sample of rows method `sample()` from class `DataFrame` can be helpful.

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:57:18.980873Z', start_time: '2021-02-03T09:57:18.978008Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

## Load US and British data in memory

```{python}
# your code here
```

## Explore the data

**QUESTION:** Look at the data, Use the attributes `columns`, `dtypes` and the methods `head`, `describe`, to get a feeling of the data.

- This dataset is supposed to report all given names used
for either sex during a year in France since 1900

- The file is made of `652 056` lines and  4 columns.

```
|-- preusuel : object
|-- nombre: int64
|-- sexe: int64
|-- annais: object
```

Each row indicates for a given `preusuel` (prénom usuel, given name), `sexe` (sex), and `annais` (année naissance, birthyear) the `nombre` (number) of babies of the given sex who were given that name during the given year.

|sexe    |preusuel     | annais|   nombre|
|:------|:--------|----:|---:|
|2     |SYLVETTE | 1953| 577|
|1   |BOUBOU   | 1979|   4|
|1   |NILS     | 1959|   3|
|2   |NICOLE   | 2003|  36|
|1   |JOSÉLITO | 2013|   4|


**QUESTION:** Compare memory usage and disk space used by data

**Hints:**

- The method `info`  prints a concise summary of a `DataFrame`.
- With optional parameter `memory_usage`, you can get an estimate
of the amount of memory used by the `DataFrame`.
- Beware that the resulting estimate depends on the argument fed.

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:42:59.360455Z', start_time: '2021-02-03T09:42:59.357825Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

**QUESTION:** Display the output of `.describe()` with style.

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:43:01.043175Z', start_time: '2021-02-03T09:43:01.040595Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

**QUESTION:** For each column compute the number of distinct values

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:43:01.392240Z', start_time: '2021-02-03T09:43:01.389193Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

# Transformations

## Improving the data types

**QUESTION:** Make `sexe` a category with two levels `Female` and `Male`. Call the new column `gender`. Do you see any reason why this factor should be ordered?

__Hint:__ Read [Pandas and categorical variables](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html?highlight=category)

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:43:02.947929Z', start_time: '2021-02-03T09:43:02.945259Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

```{python}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}

```

**QUESTION:** Compare memory usage of columns `sexe` and `gender`

```{python}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

**QUESTION:** Would it be more memory-efficient to recode `sexe` using modalities `F` and `M` instead of `Male` and `Female` ?

_Insert your answer here_

> ...

## Dealing with missing values

**QUESTION:** Variable `annais` class is `object`. Make `annais` of type `float`. Note that missing years are encoded as "XXXX", find a way to deal with that.

__Hint:__  As of releasing this Homework (2023-01-18), `Pandas` is not very good at managing missing values,
see [roadmap](https://pandas.pydata.org/docs/development/roadmap.html). Don't try to convert `annais` into an integer column.

```{python}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

## Rename and remove columns

**QUESTION:** Remove useless columns (now that you've created new ones, and rename them). You should end up with a dataframe with columns called `"gender"`, `"year"`, `"count"`, `"firstname`" with the following dtypes:

```python
gender        category
firstname     object
count         int64
year          float64
```

```{python}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

**Question:** Do the same thing for British and US data. You should eventually obtain dataframes with the same schema.  

**QUESTION:** How many missing values (NA) have been introduced? How many births are concerned?

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:58:42.294646Z', start_time: '2021-02-03T09:58:42.289319Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

**QUESTION:** Read the documentation and describe the origin of rows containing the missing values.

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:58:42.780105Z', start_time: '2021-02-03T09:58:42.777162Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

## Checkpointing: save your transformed dataframes

**QUESTION:** Save the transformed dataframe (retyped and renamed) to `./nat2021_csv.zip`. Try several compression methods.

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:58:44.434007Z', start_time: '2021-02-03T09:58:44.431292Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

**QUESTION:** Save the transformed dataframes (retyped and renamed) to `./nat2021.hdf` using `.hdf` format

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:58:45.572214Z', start_time: '2021-02-03T09:58:45.569040Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

At that point your working directory should look like:

```
├── homework01.py      # if you use `jupytext`
|── homework01.qmd     # if you use `quarto`
├── homework01.ipynb   # if you use `jupyter` `notebook`
├── babies-fr.hdf
├── babies-fr.zip
├── babies-us.hdf
├── babies-us.zip
├── babies-ew.hdf
├── babies-ew.zip
├── births-fr.csv
├── births-fr.hdf
```

**QUESTION:** Reload the data using `read_hdf(...)` so that the resulting dataframes  are properly typed with meaningful and homogeneous column names.

__Hint:__ use `try: ... except` to handle exceptions such as `FileNotFoundError`

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:58:49.413972Z', start_time: '2021-02-03T09:58:49.410965Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

## Some data "analytics" and visualization

**QUESTION**: For each year, compute the total number of Female and Male births and the proportion of Female  births among total births

__Hints:__

- Groupby operations using several columns for the groups return a dataframe with a `MultiIndex` index see [Pandas advanced](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html)

- Have a look at `MultiIndex`, `reset_index`, `pivot`, `columns.droplevel`

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:58:52.268127Z', start_time: '2021-02-03T09:58:52.265556Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

**QUESTION:** Plot the proportion of female births as a function of year and French, US, en British babynames data. Compare with what you get from `births-fr.hdf`.

Don't forget: title, axes labels, ticks, scales, etc.

Because of what we did before, the `plot` method of a `DataFrame` with be rendered using `plotly`, so you can use this. But you can use also `seaborn` or any other available plotting library that you want.

__Hint:__ Mind the missing values in the `year` column

```{python}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

**QUESTION:** Make any sensible comment about these plots.

_Insert your answer here_

> ...


**QUESTION:** Explore the fluctuations of sex ratio around its mean value since 1945  in the US, in France and in the Great Britain.

Plot deviations of sex ratio around its mean since 1945 as a function of time.

```{python}
#| ExecuteTime: {end_time: '2021-02-03T09:59:30.923060Z', start_time: '2021-02-03T09:59:30.920458Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

**QUESTION:**  Assume that baby gender is chosen at random according to a Bernoulli distribution with success probability $.48$, that baby genders are i.i.d. Perform simulations for sex ratios for French and US data since 1945. 

Plot the results, compare with your plots above.  

# The rise, decline and fall of firstnames

**Question:** For each year, country, gender and firstname, compute the popularity rank of the firstname among the names given to babies with that gender, in that country, in that year. The most popular name should be given rank $1$.  


**QUESTION:** For each firstname and sex (some names may be given to girls and boys), compute the total number of times this firstname has been given during `1900-2019`. Print the top 20 firstnames given and style your result dataframe using `background_gradient` for instance.

```{python}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

## Rare firstnames

**QUESTION:** In the French data, for each sex, plot the proportion of births given `_PRENOMS_RARES` as a function of the year.

```{python}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

# A study of the "Marie" firstname

**QUESTION:** Plot the proportion of female births given name `'MARIE'` or `'MARIE-...'` (compounded names) as a function of the year.
Proceed in such a way that the reader can see the share of compounded names. We are expecting an _area plot_.

__Hints:__

- Have a look at the `.str` accessor (to apply a string method over a whole column containing string)
- Have a look at [r-graph-gallery: stacked area](https://www.r-graph-gallery.com/stacked-area-graph.html)  and
at [ggplot documentation](https://ggplot2.tidyverse.org/reference/geom_ribbon.html). Pay attention on the way you stack the area corresponding to names matching pattern 'MARIE-.*' over or under the are corresponding to babies named 'MARIE'
- See Graphique 3, page 48, de _L'archipel français_  de J. Fourquet. Le Seuil. Essais. Vol. 898.

- Add annotation, 1st World War, Front Populaire, 2nd World War, 1968

```{python}
#| ExecuteTime: {end_time: '2021-02-03T10:00:15.046715Z', start_time: '2021-02-03T10:00:15.043807Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

# Top 10 firstnames of year 2000

**QUESTION:** For each sex, select the ten most popular names in year 2000, and plot the proportion
of newborns given that name over time. Take into account that some names might have
zero occurrence during certain years.

__Hint:__ Leave aside the rows with '_PRENOMS_RARES'.

```{python}
#| ExecuteTime: {end_time: '2021-02-03T10:00:21.360489Z', start_time: '2021-02-03T10:00:21.357427Z'}
#| jupyter: {outputs_hidden: false, source_hidden: false}
#| nteract: {transient: {deleting: false}}
# your code here
```

# Picturing concentration of babynames distributions


Every year, the name counts define a discrete probability distribution over the set of names (the universe).

This distribution, just as an income or wealth distribution, is (usually) far from being uniform. We want to assess how uneven it is.

We use the tools developed in econometrics.

Without loss of generality, we assume that we handle a distribution over positive integers $1, \ldots, n$ where $n$ is the number of distinct names given during a year.

We assume that frequencies $p_1, p_2, \ldots, p_n$ are given in ascending order, ties are broken arbitrarily.

The `Lorenz function` ([Lorenz](https://en.wikipedia.org/wiki/Lorenz_curve) not `Lorentz`) maps $[0, 1] \to [0, 1]$.

$$L(x) = \sum_{i=1}^{\lfloor nx \rfloor} p_i .$$

Note that this is a piecewise constant function. 


**Question:** Compute and plot the Lorenz fucntion for a given `sex`, `year` and `country`


**Question:** Design an animated plot that shows the evolution of the Lorenz curve of babynames distribution through the years for a given sex and country.


The Lorenz curve summarizes how far a discrete probability distribution is from the uniform distribution. This is a very rich summary and it is difficult to communicate this message to a wide audience. People tend to favor numerical indices (they don't really understand, but they get used to it): Gini, Atkinson, Theil, ...

The [Gini index](https://en.wikipedia.org/wiki/Gini_coefficient) is twice the surface of the area comprised between curves $y=x$ and $y=L(x)$.

$$G = 2 \times \int_0^1 (x -L(x)) \mathrm{d}x$$

The next formula  allows us to compute it efficiently.

$$G={\frac {2\sum _{i=1}^{n}i p_{i}}{n\sum _{i=1}^{n}p_{i}}}-{\frac {n+1}{n}}.$$


**Question:** Compute and plot Gini index of names distribution over time for sex and countries 



# Picturing surges of popularity

In the sequel, the *popularity* of a gendered name in a population during a given year is the proportion of babies of that gender born during that year in that country,  that are given this name. 

**Question:** Prepare a data frame that contains for each hype name the 20 years before and 30 years after the maximum popularity is achieved, and, for each such year, the rank and popularity of the hype name. Do this for US and French data. 


**Question:** Plot offseted popularity (share of given names within year, country, gender) curves of hype names. Facet by sex and country. 


**Question:** Rescale popularity curves so that all of them have maximum $1$. 


# Getting help

- [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/)

- [plotly](https://plotly.com/python/) for animated plots

- [stackoverflow](https://stackoverflow.com)

- [stackoverflow: pandas](https://stackoverflow.com/questions/tagged/pandas)

- [stackoverflow: plotly+python](https://stackoverflow.com/questions/tagged/plotly+python)

- The US `babynames` analogue of the INSEE file has been a playground for data scientists,
 see [https://github.com/hadley/babynames](https://github.com/hadley/babynames)

- Don't Repeat Yourself (DRY) principle  at [Wikipedia](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

