---
title: "MA7BY020 Syllabus"
---

<!-- [**Télécharger  "PDF du syllabus"**](/documents/MA7BY020-syllabus.pdf) -->


::: {.callout-note}

## Schedule

|           | Day       | Time              | Location                       |  Start |
|:---------:|:-----------:|:-------------------:|:--------------------------------|:--------|
| Lab session 1   | TBA  | TBA  | Sophie Germain TBA      | 2025-01-13 |
| Lab session 2   | TBA  | TBA  - 18:15  | Sophie Germain TBA      | 2024-01-15 |

### [{{< fa cal >}}](https://edt.math.univ-paris-diderot.fr/#/parcours/mids/m1)

:::

::: {.callout-note}

## Objectives


{{< include _objectives_ma7BY020.qmd >}}

:::

::: {.callout-note}

## [Université Paris Cité](https://u-paris.fr)

Useful links:

- [Charte Université Paris Cité](https://u-paris.fr/valeurs/)

- [Démarches et accessibilité](https://u-paris.fr/demarches-administratives-de-scolarite/)

- [Centre de contact](https://u-paris.fr/centre-de-contact/)

- [Relais handicap](https://u-paris.fr/etudes-et-handicap/)

:::


::: {.callout-note}


### Communication  {{< fa bullhorn >}}

All material is available from  [s-v-b.github.io/MA7BY020](https://s-v-b.github.io/MA7BY020)

[Moodle](https://moodle.u-paris.fr/course/view.php?id=2313)

Subscribe to [Moodle portal](https://moodle.u-paris.fr/course/view.php?id=2313) 

:::

::: {.callout-note}

### [Software](/course-support.html) {{< fa bullhorn >}}

{{< fa database >}} ...

{{< fa laptop-code >}}  

- [`R`](https://www.postgresql.org/docs/current/app-psql.html)
- [Posit](https://posit.co)
- [`rstudio`](https://posit.co/products/open-source/rstudio/)
- [`quarto`](https://quarto.org)
- [`jupyter`]
- [`vs code`]

:::


::: {.callout-note}


## References  {{< fa book >}}


- 
:::


::: {.callout-note}

### Course material  {{< fa chalkboard-teacher >}}

[Slides](/slides-listings.qmd) 

The labs are  [available](/labs-listings.qmd) (html and pdf)

Labs  corrections are [available](/corrections-listings.qmd)



:::

::: {.callout-important}

###  {{< fa graduation-cap >}}


- 3 projects:

   - $\textsf{P}_1$ 
   - $\textsf{P}_2$ 
   - $\textsf{P}_3$ 

- 2 Examinations

  - $\textsf{EST}_1$ 
  - $\textsf{EST}_2$


- Grading

$$.2 (\textsf{P}_1 + \textsf{P}_2) + . 3 \textsf{P}_3 + .1 (\textsf{EST}_1+\textsf{EST}_2)$$


:::

::: {.callout-tip}

### {{< fa wizard >}} Tips 

:::


::: {.callout-warning}

### Code of conduct

**TL;DR: No cheating!**

:::



 

::: {.callout-important}


### Save the dates !  {{< fa calendar >}}

Click [here]() for U Paris Cite Calendar.

Click [here](https://edt.math.univ-paris-diderot.fr/#/parcours/mids/m1) for M1 MIDS Calendar

:::