on:
  # push:
  #   branches: main
  # pull_request:
  #   branches: main
  workflow_dispatch:

name: Build Site

jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/install-quarto@v1

      - name: Install libcurl
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Put pandoc in PATH
        run: |
          mkdir -p ~/.local/bin
          ln -s $(dirname $(readlink -f  $(which quarto)))"/pandoc" ~/.local/bin/pandoc
        shell: bash

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Set up tinytex
        uses: r-lib/actions/setup-tinytex@v2

      - name: Add exams 
        run: |
          tlmgr update --self
          tlmgr install exams
      
      - name: Build site 🔧
        run: |
          R -e 'quarto::quarto_render(".", as_job = FALSE, output_format="html")'
          # R -e 'quarto::quarto_render("slides", as_job = FALSE, profile = "slides", use_freezer=T, quarto_args = c("--no-clean"))'
          # R -e 'quarto::quarto_render("labs-solutions", output_format="html", as_job = FALSE, profile = "solution", use_freezer=T, quarto_args = c("--no-clean"))'
          # R -e 'quarto::quarto_render("exams", output_format="html", as_job = FALSE, profile = "solution", use_freezer=T, quarto_args = c("--no-clean"))'
                    

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
